package persistance.entities;
// Generated 24 mars 2021 � 15:28:36 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CommandeId generated by hbm2java
 */
@Embeddable
public class CommandeId implements java.io.Serializable {

	private short idproduit;
	private BigDecimal idclient;
	private Short qtecommande;
	private Date datecommande;
	private Short etatcommande;

	public CommandeId() {
	}

	public CommandeId(short idproduit, BigDecimal idclient) {
		this.idproduit = idproduit;
		this.idclient = idclient;
	}

	public CommandeId(short idproduit, BigDecimal idclient, Short qtecommande, Date datecommande, Short etatcommande) {
		this.idproduit = idproduit;
		this.idclient = idclient;
		this.qtecommande = qtecommande;
		this.datecommande = datecommande;
		this.etatcommande = etatcommande;
	}

	@Column(name = "IDPRODUIT", nullable = false, precision = 4, scale = 0)
	public short getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(short idproduit) {
		this.idproduit = idproduit;
	}

	@Column(name = "IDCLIENT", precision = 22, scale = 0)
	public BigDecimal getIdclient() {
		return this.idclient;
	}

	public void setIdclient(BigDecimal idclient) {
		this.idclient = idclient;
	}

	@Column(name = "QTECOMMANDE", precision = 4, scale = 0)
	public Short getQtecommande() {
		return this.qtecommande;
	}

	public void setQtecommande(Short qtecommande) {
		this.qtecommande = qtecommande;
	}

	@Column(name = "DATECOMMANDE", length = 7)
	public Date getDatecommande() {
		return this.datecommande;
	}

	public void setDatecommande(Date datecommande) {
		this.datecommande = datecommande;
	}

	@Column(name = "ETATCOMMANDE", precision = 4, scale = 0)
	public Short getEtatcommande() {
		return this.etatcommande;
	}

	public void setEtatcommande(Short etatcommande) {
		this.etatcommande = etatcommande;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommandeId))
			return false;
		CommandeId castOther = (CommandeId) other;

		return (this.getIdproduit() == castOther.getIdproduit())
				&& ((this.getIdclient() == castOther.getIdclient()) || (this.getIdclient() != null
						&& castOther.getIdclient() != null && this.getIdclient().equals(castOther.getIdclient())))
				&& ((this.getQtecommande() == castOther.getQtecommande())
						|| (this.getQtecommande() != null && castOther.getQtecommande() != null
								&& this.getQtecommande().equals(castOther.getQtecommande())))
				&& ((this.getDatecommande() == castOther.getDatecommande())
						|| (this.getDatecommande() != null && castOther.getDatecommande() != null
								&& this.getDatecommande().equals(castOther.getDatecommande())))
				&& ((this.getEtatcommande() == castOther.getEtatcommande())
						|| (this.getEtatcommande() != null && castOther.getEtatcommande() != null
								&& this.getEtatcommande().equals(castOther.getEtatcommande())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdproduit();
		result = 37 * result + (getIdclient() == null ? 0 : this.getIdclient().hashCode());
		result = 37 * result + (getQtecommande() == null ? 0 : this.getQtecommande().hashCode());
		result = 37 * result + (getDatecommande() == null ? 0 : this.getDatecommande().hashCode());
		result = 37 * result + (getEtatcommande() == null ? 0 : this.getEtatcommande().hashCode());
		return result;
	}

}
