package persistance.entities;
// Generated 24 mars 2021 � 15:28:36 by Hibernate Tools 4.0.1.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "PRODUIT", schema = "USERTP")
public class Produit implements java.io.Serializable {

	private short idproduit;
	private Categorie categorie;
	private String desigproduit;
	private BigDecimal puproduit;
	private Short qteproduit;
	private String configproduit;
	private String marqueproduit;
	private String modeleproduit;
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Produit() {
	}

	public Produit(short idproduit) {
		this.idproduit = idproduit;
	}

	public Produit(short idproduit, Categorie categorie, String desigproduit, BigDecimal puproduit, Short qteproduit,
			String configproduit, String marqueproduit, String modeleproduit, Set<Commande> commandes) {
		this.idproduit = idproduit;
		this.categorie = categorie;
		this.desigproduit = desigproduit;
		this.puproduit = puproduit;
		this.qteproduit = qteproduit;
		this.configproduit = configproduit;
		this.marqueproduit = marqueproduit;
		this.modeleproduit = modeleproduit;
		this.commandes = commandes;
	}

	@Id

	@Column(name = "IDPRODUIT", unique = true, nullable = false, precision = 4, scale = 0)
	public short getIdproduit() {
		return this.idproduit;
	}

	public void setIdproduit(short idproduit) {
		this.idproduit = idproduit;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "IDCATEGORIE")
	public Categorie getCategorie() {
		return this.categorie;
	}

	public void setCategorie(Categorie categorie) {
		this.categorie = categorie;
	}

	@Column(name = "DESIGPRODUIT", length = 254)
	public String getDesigproduit() {
		return this.desigproduit;
	}

	public void setDesigproduit(String desigproduit) {
		this.desigproduit = desigproduit;
	}

	@Column(name = "PUPRODUIT", precision = 22, scale = 0)
	public BigDecimal getPuproduit() {
		return this.puproduit;
	}

	public void setPuproduit(BigDecimal puproduit) {
		this.puproduit = puproduit;
	}

	@Column(name = "QTEPRODUIT", precision = 4, scale = 0)
	public Short getQteproduit() {
		return this.qteproduit;
	}

	public void setQteproduit(Short qteproduit) {
		this.qteproduit = qteproduit;
	}

	@Column(name = "CONFIGPRODUIT", length = 254)
	public String getConfigproduit() {
		return this.configproduit;
	}

	public void setConfigproduit(String configproduit) {
		this.configproduit = configproduit;
	}

	@Column(name = "MARQUEPRODUIT", length = 254)
	public String getMarqueproduit() {
		return this.marqueproduit;
	}

	public void setMarqueproduit(String marqueproduit) {
		this.marqueproduit = marqueproduit;
	}

	@Column(name = "MODELEPRODUIT", length = 254)
	public String getModeleproduit() {
		return this.modeleproduit;
	}

	public void setModeleproduit(String modeleproduit) {
		this.modeleproduit = modeleproduit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "produit")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
